# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unique/Work/opencv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unique/Work/opencv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unique/Work/opencv/CMakeFiles /home/unique/Work/opencv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unique/Work/opencv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_qrcode

# Build rule for target.
opencv_qrcode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_qrcode
.PHONY : opencv_qrcode

# fast build rule for target.
opencv_qrcode/fast:
	$(MAKE) -f CMakeFiles/opencv_qrcode.dir/build.make CMakeFiles/opencv_qrcode.dir/build
.PHONY : opencv_qrcode/fast

#=============================================================================
# Target rules for targets named opencv_example

# Build rule for target.
opencv_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_example
.PHONY : opencv_example

# fast build rule for target.
opencv_example/fast:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/build
.PHONY : opencv_example/fast

#=============================================================================
# Target rules for targets named opencv_detect

# Build rule for target.
opencv_detect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_detect
.PHONY : opencv_detect

# fast build rule for target.
opencv_detect/fast:
	$(MAKE) -f CMakeFiles/opencv_detect.dir/build.make CMakeFiles/opencv_detect.dir/build
.PHONY : opencv_detect/fast

detect.o: detect.cpp.o

.PHONY : detect.o

# target to build an object file
detect.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_detect.dir/build.make CMakeFiles/opencv_detect.dir/detect.cpp.o
.PHONY : detect.cpp.o

detect.i: detect.cpp.i

.PHONY : detect.i

# target to preprocess a source file
detect.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_detect.dir/build.make CMakeFiles/opencv_detect.dir/detect.cpp.i
.PHONY : detect.cpp.i

detect.s: detect.cpp.s

.PHONY : detect.s

# target to generate assembly for a file
detect.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_detect.dir/build.make CMakeFiles/opencv_detect.dir/detect.cpp.s
.PHONY : detect.cpp.s

example.o: example.cpp.o

.PHONY : example.o

# target to build an object file
example.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/example.cpp.o
.PHONY : example.cpp.o

example.i: example.cpp.i

.PHONY : example.i

# target to preprocess a source file
example.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/example.cpp.i
.PHONY : example.cpp.i

example.s: example.cpp.s

.PHONY : example.s

# target to generate assembly for a file
example.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/example.cpp.s
.PHONY : example.cpp.s

qrcode.o: qrcode.cpp.o

.PHONY : qrcode.o

# target to build an object file
qrcode.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_qrcode.dir/build.make CMakeFiles/opencv_qrcode.dir/qrcode.cpp.o
.PHONY : qrcode.cpp.o

qrcode.i: qrcode.cpp.i

.PHONY : qrcode.i

# target to preprocess a source file
qrcode.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_qrcode.dir/build.make CMakeFiles/opencv_qrcode.dir/qrcode.cpp.i
.PHONY : qrcode.cpp.i

qrcode.s: qrcode.cpp.s

.PHONY : qrcode.s

# target to generate assembly for a file
qrcode.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_qrcode.dir/build.make CMakeFiles/opencv_qrcode.dir/qrcode.cpp.s
.PHONY : qrcode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... opencv_qrcode"
	@echo "... opencv_example"
	@echo "... rebuild_cache"
	@echo "... opencv_detect"
	@echo "... detect.o"
	@echo "... detect.i"
	@echo "... detect.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... qrcode.o"
	@echo "... qrcode.i"
	@echo "... qrcode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

